version: '3.3'

services:
  minecraft:
    build: .
    volumes:
      - minecraft-data:/data
    ports:
      - "25565:25595"
      - "25575:25575"
    restart: always
volumes:
  minecraft-data:
    driver: local
